version: '3'

services:
    mysql:
        image: mariadb:10.5
        restart: on-failure
        ports:
            - 3306:3306
        volumes:
            - ./.mysql:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}

    php:
        depends_on:
            - mysql
        build: build/php
        restart: on-failure
        volumes:
            - ./application/:/var/www/application/
        environment:
            - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@mysql:3306/${DATABASE_NAME}?serverVersion=5.7

    nginx:
        depends_on:
            - php
        image: nginx:alpine
        restart: on-failure
        ports:
            - 80:80
        volumes_from:
            - php
        volumes:
            - ./build/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./build/nginx/sites/:/etc/nginx/sites-available
            - ./build/nginx/conf.d/:/etc/nginx/conf.d
            - ./logs:/var/log

    phpmyadmin:
        depends_on:
            - mysql
        image: phpmyadmin/phpmyadmin
        restart: on-failure
        environment:
            PMA_HOST: mysql
        ports:
            - 8080:80
        links:
            - mysql

    mailhog:
        image: mailhog/mailhog:latest
        ports:
            - "8025:8025"
